import { Patch, User } from './types.ts'

export const mockUsers: Array<User> = [
  {
    name: 'John',
    surname: 'Doe',
    telegramUser: 'john_doe',
    mail: 'john@example.com',
  },
  {
    name: 'Jane',
    surname: 'Smith',
    telegramUser: 'jane_smith',
    mail: 'jane@example.com',
  },
]

export const mockPatches: Array<Patch> = [
  {
    id: '1',
    owner: mockUsers[0],
    title: 'Vintage Stamp Collection',
    description: 'A collection of rare and vintage stamps from around the world.',
    image: 'stamp_collection.jpg',
    categories: ['Collectibles', 'Philately'],
    isTradeable: true,
  },
  {
    id: '2',
    owner: mockUsers[1],
    title: 'Antique Coin Set',
    description: 'A set of antique coins from various historical periods.',
    image: 'coin_set.jpg',
    categories: ['Collectibles', 'Numismatics'],
    isTradeable: true,
  },
  {
    id: '3',
    owner: mockUsers[0],
    title: 'Rare Book Collection',
    description: 'A collection of rare and antique books from different genres.',
    image: 'book_collection.jpg',
    categories: ['Books', 'Collectibles'],
    isTradeable: true,
  },
  {
    id: '4',
    owner: mockUsers[1],
    title: 'Vintage Vinyl Records',
    description: 'A collection of classic vinyl records in excellent condition.',
    image: 'vinyl_records.jpg',
    categories: ['Music', 'Collectibles'],
    isTradeable: true,
  },
  {
    id: '5',
    owner: mockUsers[0],
    title: 'Classic Car Models',
    description: 'Miniature models of classic cars from the 20th century.',
    image: 'car_models.jpg',
    categories: ['Collectibles', 'Automobilia'],
    isTradeable: true,
  },
  {
    id: '6',
    owner: mockUsers[1],
    title: 'Vintage Postcard Set',
    description: 'A set of vintage postcards from various destinations.',
    image: 'postcard_set.jpg',
    categories: ['Collectibles', 'Philately'],
    isTradeable: true,
  },
  {
    id: '7',
    owner: mockUsers[0],
    title: 'Ancient Artifacts',
    description: 'A collection of ancient artifacts from different civilizations.',
    image: 'artifact_collection.jpg',
    categories: ['Archaeology', 'Collectibles'],
    isTradeable: true,
  },
  {
    id: '8',
    owner: mockUsers[1],
    title: 'Classic Movie Poster Prints',
    description: 'Reproduction prints of classic movie posters.',
    image: 'movie_posters.jpg',
    categories: ['Movies', 'Collectibles'],
    isTradeable: true,
  },
  {
    id: '9',
    owner: mockUsers[0],
    title: 'Vintage Toy Collection',
    description: 'A collection of vintage toys from the 20th century.',
    image: 'toy_collection.jpg',
    categories: ['Collectibles', 'Toys'],
    isTradeable: true,
  },
  {
    id: '10',
    owner: mockUsers[1],
    title: 'Rare Comic Books',
    description: 'A selection of rare and collectible comic books.',
    image: 'comic_books.jpg',
    categories: ['Books', 'Collectibles'],
    isTradeable: true,
  },
]

export const ownUser: User = {
  name: 'Rick',
  surname: 'Sánchez',
  telegramUser: 'rick_sanchez',
  mail: 'rick@sanchez.com',
  password: '1234',
}

export const mockOwnPatches: Array<Patch> = [
  {
    id: '11',
    owner: ownUser,
    title: 'Vintage Watch Collection',
    description: 'A collection of vintage wristwatches from various brands.',
    image: 'watch_collection.jpg',
    categories: ['Collectibles', 'Watches'],
    isTradeable: true,
  },
  {
    id: '12',
    owner: ownUser,
    title: 'Rare Art Prints',
    description: 'A series of limited edition art prints from renowned artists.',
    image: 'art_prints.jpg',
    categories: ['Art', 'Collectibles'],
    isTradeable: true,
  },
  {
    id: '13',
    owner: ownUser,
    title: 'Vintage Camera Set',
    description: 'A set of vintage film cameras in excellent working condition.',
    image: 'camera_set.jpg',
    categories: ['Photography', 'Collectibles'],
    isTradeable: true,
  },
  {
    id: '14',
    owner: ownUser,
    title: 'Rare Stamp Collection',
    description: 'A collection of rare and valuable stamps from different eras.',
    image: 'rare_stamps.jpg',
    categories: ['Collectibles', 'Philately'],
    isTradeable: true,
  },
  {
    id: '15',
    owner: ownUser,
    title: 'Vintage Poster Collection',
    description: 'A collection of vintage posters from various cultural events.',
    image: 'poster_collection.jpg',
    categories: ['Collectibles', 'Art'],
    isTradeable: true,
  },
]